package dev.bytelore.server;

import com.sun.net.httpserver.HttpsConfigurator;
import com.sun.net.httpserver.HttpsParameters;
import com.sun.net.httpserver.HttpsServer;
import java.io.File;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyStore;
import java.security.SecureRandom;
import java.util.Locale;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;
import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLEngine;

/**
 * A local HTTPS server standing in for a whitelist source's feed and verify endpoints in tests, so
 * the pipeline suite never reaches the real internet.
 *
 * <p>HTTPS, not plain HTTP: {@code whitelist_sources.feed_url} and {@code verify_url_pattern} carry
 * a database {@code CHECK} constraint requiring an absolute {@code https://} URL (§7.9 of the REST
 * contract -- "the trust chain cannot start on a channel anyone can rewrite"), so a fixture row can
 * only ever be inserted with an {@code https://} address, and the pipeline's {@code
 * PipelineHttpClient} then really does dial it over TLS.
 *
 * <p>The certificate is a throwaway self-signed one generated by shelling out to the JDK's own
 * {@code keytool} (bundled with every JDK, including the one running this suite) rather than by
 * reaching for an internal {@code sun.security} API. The test-side {@code HttpClient} that trusts
 * it is wired separately, in {@code BlogPipelineIT}'s {@code @TestConfiguration}.
 */
final class FakeHttpsFeedServer implements AutoCloseable {

  private static final String KEYSTORE_PASSWORD = "changeit";

  private final HttpsServer server;

  private FakeHttpsFeedServer(HttpsServer server) {
    this.server = server;
  }

  static FakeHttpsFeedServer start() throws Exception {
    KeyStore keyStore = generateSelfSignedKeyStore();

    SSLContext sslContext = SSLContext.getInstance("TLS");
    KeyManagerFactory keyManagerFactory =
        KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
    keyManagerFactory.init(keyStore, KEYSTORE_PASSWORD.toCharArray());
    sslContext.init(keyManagerFactory.getKeyManagers(), null, new SecureRandom());

    HttpsServer server = HttpsServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
    server.setHttpsConfigurator(
        new HttpsConfigurator(sslContext) {
          @Override
          public void configure(HttpsParameters params) {
            SSLEngine engine = sslContext.createSSLEngine();
            params.setNeedClientAuth(false);
            params.setCipherSuites(engine.getEnabledCipherSuites());
            params.setProtocols(engine.getEnabledProtocols());
            params.setSSLParameters(sslContext.getDefaultSSLParameters());
          }
        });
    server.setExecutor(Executors.newCachedThreadPool());
    server.start();
    return new FakeHttpsFeedServer(server);
  }

  String baseUrl() {
    return "https://127.0.0.1:" + server.getAddress().getPort();
  }

  /** Serves a fixed response for one exact path. */
  void respond(String path, int status, String body) {
    server.createContext(
        path,
        exchange -> {
          byte[] bytes = body.getBytes(StandardCharsets.UTF_8);
          exchange.getResponseHeaders().add("Content-Type", "application/xml; charset=utf-8");
          exchange.sendResponseHeaders(status, bytes.length);
          try (OutputStream out = exchange.getResponseBody()) {
            out.write(bytes);
          }
        });
  }

  /**
   * Serves a response computed from the request path, for a whole subtree -- used for a verify
   * endpoint whose path carries the version being confirmed.
   */
  void respondDynamic(String pathPrefix, Function<String, HandlerResult> handler) {
    server.createContext(
        pathPrefix,
        exchange -> {
          HandlerResult result = handler.apply(exchange.getRequestURI().getPath());
          byte[] bytes = result.body().getBytes(StandardCharsets.UTF_8);
          exchange.getResponseHeaders().add("Content-Type", "text/plain; charset=utf-8");
          exchange.sendResponseHeaders(result.status(), bytes.length);
          try (OutputStream out = exchange.getResponseBody()) {
            out.write(bytes);
          }
        });
  }

  record HandlerResult(int status, String body) {}

  @Override
  public void close() {
    server.stop(0);
  }

  private static KeyStore generateSelfSignedKeyStore() throws Exception {
    Path dir = Files.createTempDirectory("bytelore-pipeline-it");
    Path keystorePath = dir.resolve("fake-server.p12");
    boolean windows = System.getProperty("os.name", "").toLowerCase(Locale.ROOT).contains("win");
    String keytool =
        System.getProperty("java.home")
            + File.separator
            + "bin"
            + File.separator
            + "keytool"
            + (windows ? ".exe" : "");

    ProcessBuilder builder =
        new ProcessBuilder(
            keytool,
            "-genkeypair",
            "-alias",
            "bytelore-pipeline-test",
            "-keyalg",
            "RSA",
            "-keysize",
            "2048",
            "-validity",
            "2",
            "-keystore",
            keystorePath.toString(),
            "-storetype",
            "PKCS12",
            "-storepass",
            KEYSTORE_PASSWORD,
            "-keypass",
            KEYSTORE_PASSWORD,
            "-dname",
            "CN=localhost",
            "-ext",
            "SAN=dns:localhost,ip:127.0.0.1");
    builder.redirectErrorStream(true);
    Process process = builder.start();
    String output;
    try (InputStream in = process.getInputStream()) {
      output = new String(in.readAllBytes(), StandardCharsets.UTF_8);
    }
    boolean finished = process.waitFor(30, TimeUnit.SECONDS);
    if (!finished || process.exitValue() != 0) {
      throw new IllegalStateException("keytool failed to generate a test keystore: " + output);
    }

    KeyStore keyStore = KeyStore.getInstance("PKCS12");
    try (InputStream in = Files.newInputStream(keystorePath)) {
      keyStore.load(in, KEYSTORE_PASSWORD.toCharArray());
    }
    return keyStore;
  }
}
